=== LinuxSuRen/phoenix.webui.framework/example/autotest.web.framework/src/main/resources/autotest.web.framework.suite.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://suite.surenpi.com"
	xmlns:suren="http://suite.surenpi.com"
	elementFormDefault="qualified">
	<xs:element name="suite">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="page" type="suren:pageType" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>
							<![CDATA[用于测试的Page类配置。]]>
						</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="pageConfig" type="xs:string">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[当前测试流程使用的Page描述文件。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="pagePackage" type="xs:string">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[公用的Page类包]]>
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="rows" type="xs:string" default="1">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[当前测试流程使用的数据集合，例如：1...3,5,7，默认执行第一组数据。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="lackLines" type="suren:lackLinesEnum" default="nearby">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[当前缺少指定数据组时的具体行为，默认将会采用最近的数据组。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="errorLines" type="suren:errorLinesEnum" default="stop">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[当使用当前数据组运行报错时的具体行为，默认将会停止程序。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="afterSleep" type="xs:long" default="0">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[测试套件运行结束后的休眠时间（毫秒）。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="pageType">
		<xs:sequence>
			<xs:element name="actions" type="suren:actionsType">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="class" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					<![CDATA[Page类对应的全路径，必填。]]>
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="actionsType">
		<xs:annotation>
			<xs:documentation>
				<![CDATA[操作集合，必填。]]>
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="action" type="suren:actionType" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[具体的操作描述，必填。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="suren:commonActionAttr">
		</xs:attributeGroup>
	</xs:complexType>

	<xs:complexType name="actionType">
		<xs:attribute name="field" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					<![CDATA[动作对应Page类中的属性名称（大小写敏感）。]]>
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="name" type="suren:actionEnum" default="click">
			<xs:annotation>
				<xs:documentation>
					<![CDATA[动作对应的操作名。]]>
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attributeGroup ref="suren:commonActionAttr">
		</xs:attributeGroup>
	</xs:complexType>
	
	<xs:attributeGroup name="commonActionAttr">
		<xs:attribute name="beforeSleep" type="xs:int" default="0">
			<xs:annotation>
				<xs:documentation>
					<![CDATA[操作前的休眠时间（单位：毫秒），可选。]]>
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="afterSleep" type="xs:int" default="0">
			<xs:annotation>
				<xs:documentation>
					<![CDATA[操作后的休眠时间（单位：毫秒），可选。]]>
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="disable" type="xs:boolean" default="false">
			<xs:annotation>
				<xs:documentation>
					<![CDATA[是否禁用该操作，true为禁用，false为启用，可选。]]>
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="repeat" type="xs:positiveInteger" default="1">
			<xs:annotation>
				<xs:documentation>
					<![CDATA[重复次数（默认为：1），可选。]]>
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="rows" type="xs:string" default="1">
			<xs:annotation>
				<xs:documentation>
					<![CDATA[指定数据行数（默认为：1），可选。]]>
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
		
	<xs:simpleType name="actionEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="fillValue">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[填入文本。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="click">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[单击。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="enter">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[回车键。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="upload">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[上传文件。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="selectByValue">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[根据Option的value选择。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="selectByIndex">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[根据序号选择，从0开始。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="selectByText">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[根据文本选择。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="select">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[根据文本选择。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="hover">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[鼠标悬停。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="lackLinesEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="error">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[当前缺少指定数据组时报错。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="nearby">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[当前缺少指定数据组时使用最近的数据组。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="errorLinesEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="stop">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[当使用当前数据组运行报错时停止程序。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="continue">
				<xs:annotation>
					<xs:documentation>
						<![CDATA[当使用当前数据组运行报错时忽略并继续程序。]]>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== LinuxSuRen/phoenix.webui.framework/src/test/resources/suiteRunner/xml/maimai_runner.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--Auto created by AutoTest, 17-1-1 下午8:47 -->
<suren:suite xmlns:suren="http://suite.surenpi.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://suite.surenpi.com
		http://surenpi.com/schema/suite/autotest.web.framework.suite.xsd "
	pageConfig="maimai.xml" afterSleep="3000">
	<suren:page class="autotest.demo.maimai.page.HomePage">
		<suren:actions>
			<suren:action field="toLoginBut" name="click" />
		</suren:actions>
	</suren:page>
	<suren:page class="autotest.demo.maimai.page.LoginPage">
		<suren:actions>
			<suren:action field="commonBut" name="invoke" invoker="JsInvoker"
				afterSleep="3000" disable="true">
				<suren:param value="alert(1);" />
				<suren:param value="window.location='http://surenpi.com';" />
			</suren:action>
			<suren:action field="phone" name="fillValue" />
			<suren:action field="password" name="fillValue" />
			<suren:action field="loginBut" name="click" />
		</suren:actions>
	</suren:page>
	<suren:page class="autotest.demo.maimai.page.MenuPage">
		<suren:actions>
			<suren:action field="gossipBut" name="click" />
		</suren:actions>
	</suren:page>
	<suren:page class="autotest.demo.maimai.page.SSIPPage">
		<suren:actions>
			<suren:action field="inputPanel" name="fillValue" />
			<suren:action field="postBut" name="click" />
		</suren:actions>
	</suren:page>
</suren:suite>
